// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfSjRfxO3cRTQVI_0pl-Q_zJDcYvIuOQI',
    appId: '1:643914377626:web:4d213744e7dbd3d063b223',
    messagingSenderId: '643914377626',
    projectId: 'ecloset-f1f4f',
    authDomain: 'ecloset-f1f4f.firebaseapp.com',
    storageBucket: 'ecloset-f1f4f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    databaseURL:
        "https://ecloset-f1f4f-default-rtdb.asia-southeast1.firebasedatabase.app",
    apiKey: 'AIzaSyDZAhEtxJ0zygawLtZmR7MYA_1M7yZ1Yhg',
    appId: '1:643914377626:android:bc94ec7da09f4ed763b223',
    messagingSenderId: '643914377626',
    projectId: 'ecloset-f1f4f',
    storageBucket: 'ecloset-f1f4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuFIkMBWqJ0309979WrL-EUs2z_sRIxyg',
    appId: '1:643914377626:ios:001aeb37a1a3baa763b223',
    messagingSenderId: '643914377626',
    projectId: 'ecloset-f1f4f',
    storageBucket: 'ecloset-f1f4f.appspot.com',
    iosClientId:
        '643914377626-0gt3k9cbspbgctqi3bu8agc2m08tch2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecloset',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuFIkMBWqJ0309979WrL-EUs2z_sRIxyg',
    appId: '1:643914377626:ios:001aeb37a1a3baa763b223',
    messagingSenderId: '643914377626',
    projectId: 'ecloset-f1f4f',
    storageBucket: 'ecloset-f1f4f.appspot.com',
    iosClientId:
        '643914377626-0gt3k9cbspbgctqi3bu8agc2m08tch2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecloset',
  );
}
